# Base configs
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-125032359-1"

# UI configs
title: "Photography by Khen Daniel"
subtitle: "Capturing moments. Creating memories. Captivating hearts"
author: "Khen Daniel"
header:
 title: "Photography"
 subtitle: "by Khen Daniel"
footer:
 name: "Hey there, my name is Khen"
 bio: "I am a software engineer from Philippines. Always hacking through technology and started loving photography"
 github: "<button href=\"https://github.com/thekhenzie/photography\">fork me on github</a> ;)"
web_design: "KD"
social_urls:
  facebook: "https://www.facebook.com/haroldbaniqued"
  twitter: "https://www.twitter.com/khndii"
  instagram: "https://www.instagram.com/kingkheeen"
  linkedin: "https://www.linkedin.com/in/harold-khen-baniqued-b2422a125/"
  github: "https://www.github.com/thekhenzie"
